Repository crystal-lang/distribution-scripts, pull requests merged in 2024-08, with the labels that each got.

#326 Fix update bin directory in linux build instructions
  linux/Dockerfile
Labels: bug

#325 Add installer test for Amazon Linux 2023
  packages/test-install-on-docker.sh
  packages/test/amazon.bats
Labels: enhancement

#323 Update distro inference strategy to handle dnf based systems
  packages/scripts/install.sh
Labels: enhancement

#324 Update dnf installation to be compatible with microdnf
  packages/scripts/install.sh
Labels: enhancement

#327 Mention `shard.yml` in Crystal release process
  processes/crystal-release.md
Labels: enhancement

#329 Drop package install test for CentOS stream
  packages/test/centos.bats
Labels: chore
